task9/app/urls.py
from app import views
from django.urls import path

app_name = 'app'

urlpatterns = [
    path('', views.ListUserView.as_view(), name='users'),
    path('detail/<int:pk>/', views.DetailUserView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.EditUserView.as_view(), name='edit'),
    path('remove/<int:pk>/', views.RemoveUserView.as_view(), name='remove'),
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('about/', views.AboutView.as_view(), name='about'),
]

task9/manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task9/app/templates/app/users/create.html
{% extends 'app/base.html' %}

{% block title %}Edit user {{ user.id }} {% endblock %}

{% block pagename %}Edit user {{ user.id }} {% endblock %}

{% block body %}
    <div class="block">
        <a class="link margin_r_20" href="{% url 'app:users' %}">List</a>
    </div>

    <form action="{% url 'app:create' %}" class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if error %}
            <div class="error">{{ error }}</div>
        {% endif %}

        <div class="form__form">
        {% for field in form %}
            <div class="form__row">
                <div class="form__label">{{ field.label_tag }}</div>
                <div class="form__field form__field_{{ field.name }}">
                    {{ field }}
                </div>
                <div class="form__error">{{ field.errors }}</div>
            </div>
        {% endfor %}

        {% for field in form_profile %}
        <div class="form__row">
            <div class="form__label">{{ field.label_tag }}</div>
            <div class="form__field form__field_{{ field.name }}">
                {{ field }}
            </div>
            <div class="form__error">{{ field.errors }}</div>
        </div>
        {% endfor %}
        </div>

        <div class="form__tools">
            <input type="submit" value="Create" class="button">
        </div>
    </form>
{% endblock %}

task9/app/templates/app/users/detail.html
{% extends 'app/base.html' %}

{% block title %}Edit user {{ user.id }} {% endblock %}

{% block pagename %}Edit user {{ user.id }} {% endblock %}

{% load translate_status %}

{% block body %}
    <div class="block">
        <a class="link margin_r_20" href="{% url 'app:users' %}">List</a><br/><br/>
        <a class="link margin_r_20" href="{% url 'app:edit' user.id %}">Edit user</a>
    </div>

    <div class="block text">
        <p class="margin_b_10">
            {% if user.photo %}
                <div class="avatar" style="background-image: url('{{ user.photo.url }}')"></div>
            {% endif %}
        </p>
        <p class="margin_b_10">First name: <b>{{ user.first_name }}</b></p>
        <p class="margin_b_10">Last name: <b>{{ user.last_name }}</b></p>
        <p class="margin_b_10">E-mail: <b>{{ user.email }}</b></p>
        <p class="margin_b_10">Department: <b>{{ user.profile.department }}</b></p>
        <p class="margin_b_10">Secure code: <b>{{ user.profile.secure_code }}</b></p>
        <p class="margin_b_10">Status: <b>{{ user.profile.status | translate_status }}</b></p>
    </div>
    <div class="block">
    </div>
{% endblock %}

task9/app/templates/app/users/edit.html
{% extends 'app/base.html' %}

{% block title %}Edit user {{ user.id }} {% endblock %}

{% block pagename %}Edit user {{ user.id }} {% endblock %}

{% block body %}
    <div class="block">
        <a class="link margin_r_20" href="{% url 'app:users' %}">List</a>
    </div>

    <form action="{% url 'app:edit' user.id %}" class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if error %}
            <div class="error">{{ error }}</div>
        {% endif %}

        <div class="form__form">
        {% for field in form %}
            <div class="form__row">
                <div class="form__label">{{ field.label_tag }}</div>
                <div class="form__field form__field_{{ field.name }}">
                    {{ field }}
                </div>
                <div class="form__error">{{ field.errors }}</div>
            </div>
        {% endfor %}

        {% for field in form_profile %}
        <div class="form__row">
            <div class="form__label">{{ field.label_tag }}</div>
            <div class="form__field form__field_{{ field.name }}">
                {{ field }}
            </div>
            <div class="form__error">{{ field.errors }}</div>
        </div>
        {% endfor %}
        </div>

        <div class="form__tools">
            <input type="submit" value="Save" class="button">
            <a class="link color_red" href="{% url 'app:remove' user.id %}">Remove</a>
        </div>
    </form>
{% endblock %}

task9/app/templates/app/users/list.html
{% extends 'app/base.html' %}

{% block title %}Page users{% endblock %}

{% block pagename %}Users{% endblock %}

{% load translate_status %}

{% block body %}
    <div class="block">
        <a class="link margin_r_20" href="{% url 'app:create' %}">Create</a>
    </div>

    <table class="table">
        <thead class="table__thead">
            <th class="table__th table__th_id">Id</th>
            <th class="table__th">First name</th>
            <th class="table__th">Last name</th>
            <th class="table__th">E-mail</th>
            <th class="table__th">Department</th>
            <th class="table__th">Secure code</th>
            <th class="table__th">Status</th>
            <th class="table__th">Actions</th>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td class="table__td">
                    <a href="{% url 'app:detail' user.id %}">{{ user.id }}</a>
                </td>
                <td class="table__td">
                    <div class="table__td__photo">
                        {% if user.photo %}
                            <a href="{% url 'app:detail' user.id %}" class="avatar" style="background-image: url('{{ user.photo.url }}')"></a>
                        {% else %}
                            <a href="{% url 'app:detail' user.id %}" class="avatar"></a>
                        {% endif %}
                        <a href="{% url 'app:detail' user.id %}">{{ user.first_name }}</a>
                    </div>
                </td>
                <td class="table__td">{{ user.last_name }}</td>
                <td class="table__td">{{ user.email }}</td>
                <td class="table__td">{{ user.profile.department }}</td>
                <td class="table__td">{{ user.profile.secure_code }}</td>
                <td  class="table__td">{{ user.profile.status | translate_status }}</td>
                <td  class="table__td">
                    <a href="{% url 'app:edit' user.id %}">Edit</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

task9/app/templates/app/users/remove.html
{% extends 'app/base.html' %}

{% block title %}Remove user {{ user.id }} {% endblock %}

{% block pagename %}Remove user {{ user.id }} {% endblock %}

{% block body %}
    <div class="block">
        Are you sure you want to delete the user ?
    </div>

    <form action="{% url 'app:remove' user.id %}" class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if error %}
            <div class="error">{{ error }}</div>
        {% endif %}

        <div class="form__tools" style="width: 300px">
            <input type="submit" value="Yes" class="button">
            <a class="button button_danger" href="{% url 'app:users' %}">No</a>
        </div>
    </form>

{% endblock %}