task9/app/urls.py
from app import views
from django.urls import path

app_name = 'app'

urlpatterns = [
    path('', views.ListUserView.as_view(), name='users'),
    path('detail/<int:pk>/', views.DetailUserView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.EditUserView.as_view(), name='edit'),
    path('remove/<int:pk>/', views.RemoveUserView.as_view(), name='remove'),
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('about/', views.AboutView.as_view(), name='about'),
]

task9/manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task9/app/templates/app/about.html
{% extends 'app/base.html' %}

{% block title %}Page about{% endblock %}

{% block pagename %}About{% endblock %}

{% block body %}
<div class="text">
    This id demonstration page - a home work on django using <b>ORM</b>, <b>Debug tool</b> and <b>Docker-compose</b>
</div>
{% endblock %}

task9/app/templates/app/base.html
<!doctype html>
<html lang="en">
<head>
	<base href="/">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta id="appViewport" name="viewport" content="width=device-width, initial-scale=1">

	<title>{% block title %}{% endblock %}</title>

    {% load static %}
	<link href="{% static 'reset.css' %}" rel="stylesheet">
    <link href="{% static 'fonts.css' %}" rel="stylesheet">
    <link href="{% static 'headline.css' %}" rel="stylesheet">
    <link href="{% static 'table.css' %}" rel="stylesheet">
    <link href="{% static 'form.css' %}" rel="stylesheet">
    <link href="{% static 'icons.css' %}" rel="stylesheet">
    <link href="{% static 'main.css' %}" rel="stylesheet">

</head>

<body>
    {% include 'app/headline.html' %}
    <div class="page page_title">
        <div class="page__inner">
            <h1 class="hdr">{% block pagename %}{% endblock %}</h1>
        </div>
    </div>

    <div class="page page_default">
        <div class="page__inner">
            {% block body %}{% endblock %}
        </div>
    </div>
</body>

</html>

task9/app/templates/app/headline.html
<div class="page headline headline_blue">
    <div class="page__inner headline__inner">

        <a href="{% url 'app:users' %}" class="headline__title">Otus django work</a>

        <div class="headline__menu">
            <a href="{% url 'app:users' %}"
               class="headline__menu__item{% if page == 'users' %} headline__menu__item_active{% endif %}"
            >Users</a>
            <a href="{% url 'app:about' %}"
               class="headline__menu__item{% if page == 'about' %} headline__menu__item_active{% endif %}"
            >About</a>
        </div>

        <div class="headline__tools">
            <a href="{% url 'admin:index' %}" class="headline__tools__item" title="Goto admin">
                <span class="icon icon_admin"></span>
            </a>
        </div>

    </div>
</div>